// var str = 'Hello, World!';
// var str2 = str.slice(2, 9);
// // console.log(str2);
// // console.log(str);
// var str3 = str.slice(-2);
// console.log(str3);
var tags = 'meat, ham, salami, pork, beef, chicken';
// console.log(tags);
var tagsArray = tags.replace(/,/g, '').split(' ');
console.log(tagsArray);
